//Para requisições com body:
//Content-Type: application/json

//Para requisições com headers
//Authorization: "token

###
POST http://localhost:3003/users
Content-Type: application/json

{
    "name": "luan",
    "email": "luan@labenu.com",
    "password": "luan123"
}

###
GET http://localhost:3003/users 

###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "produto6",
    "price": 43,
    "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

###
GET http://localhost:3003/products

###
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "user_id": "001",
    "product_id": "001",
    "quantity": 2
}

###
GET http://localhost:3003/purchases