//Para requisições com body:
//Content-Type: application/json

//Para requisições com headers
//Authorization: "token"

###
GET http://localhost:3003/clients

###
GET http://localhost:3003/clients/Thaynara/Balance?cpf=222.222.333-45

###
POST http://localhost:3003/createAccount
Content-Type: application/json

{
    "name": "walmir de Souza Figueiredo Junior",
    "cpf": "174.098.347-57",
    "birthDate": "30/04/2001"
}

###
PUT http://localhost:3003/clients/addBalance
Content-Type: application/json

{
    "name": "Thaynara",
    "cpf": "222.222.333-45",
    "value": 400
}

###
PUT http://localhost:3003/clients/4b7aa200-2e5a-4039-9ddc-0f83f1064125/payment
Content-Type: application/json

{
    "value": 4000,
    "description": "boleto",
    "date": "30/04/2001"
}


###
PUT http://localhost:3003/clienst/transfer
Content-Type: application/json

{
    "senderName": "pétala",
    "senderCpf": "111.222.333-45",
    "recipientName": "thaynara",
    "recipientCpf": "222.222.333-45",
    "value": 30
}